# Site settings
title: Semih Onay
description: 'Graduated from Istanbul Bilgi University Department of Computer Science. My interest are
Neuroscience, Cognition and Computer Games'
url: 'semyonic.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Semih Onay'
  email: semih.onay@bilgiedu.net
  twitter_username: Semyonic
  github_username:  Semyonic
  linkedin_username:  semihonay

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments
gems: [jekyll-paginate]

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
